apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30000  # Puedes elegir el puerto que desees
  selector:
    app: elasticsearch
