apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  type: NodePort
  ports:
    - port: 5044
      targetPort: 5044
      nodePort: 30006
    - port: 9600
      targetPort: 9600
      nodePort: 30005
  selector:
    app: logstash
