apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
    - name: logstash-tcp
      port: 5044
      targetPort: 5044
    - name: logstash-http
      port: 9600
      targetPort: 9600
  type: ClusterIP
