service:
  type: NodePort
  port: 80
  nodePort: 30003

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: "http://prometheus-server:9090"
        access: proxy
        isDefault: true
