apiVersion: v1
kind: Service
metadata:
  name: flask-tienda-service
spec:
  selector:
    app: flask-tienda
  ports:
    - protocol: TCP
      port: 80      # Puerto interno del contenedor (si es diferente de 80, cámbialo)
      targetPort: 5000  # Puerto donde Flask está escuchando
      nodePort: 30001   # Puerto en el nodo (puedes elegir otro número de puerto)
  type: NodePort
