apiVersion: v1
kind: Service
metadata:
  name: flask-tienda-service
spec:
  selector:
    app: flask-tienda
  ports:
    - protocol: TCP
      port: 80        # El puerto en el que el servicio estará accesible dentro del clúster
      targetPort: 5000 # El puerto en el que tu aplicación Flask está escuchando dentro del contenedor
  type: LoadBalancer   # Si estás usando un balanceador de carga, esto expondrá el servicio al exterior
