name: Build and Deploy Flask App with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Revisar el código
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar Docker Buildx (requerido para construir imágenes multi-plataforma)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Actualiza a la versión más reciente

      # Paso 3: Iniciar sesión en GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Paso 4: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/flask_tienda:latest .

      # Paso 5: Subir la imagen Docker a GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/flask_tienda:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Paso 1: Revisar el código
      - name: Check out code
        uses: actions/checkout@v2

      # Paso 2: Configurar kubectl para interactuar con tu clúster de Kubernetes
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # Paso 3: Desplegar en Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
