#name: Build and Deploy Flask App with Docker

#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

#jobs:
#  build:
#    runs-on: self-hosted  # Cambiado a un runner en tu red local

#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2#
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2#

#      - name: Log in to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GHCR_TOKEN }}

#      - name: Build Docker image
#        run: |
#          docker build -t ghcr.io/${{ github.repository }}/flask_tienda:latest .
#
#      - name: Push Docker image
#        run: |
#          docker push ghcr.io/${{ github.repository }}/flask_tienda:latest

#  deploy:
#    runs-on: self-hosted  # Cambiado a un runner en tu red local
#    needs: build

#    steps:
#      - name: Check out code
#        uses: actions/checkout@v2

#      - name: Install kubectl
#        run: |
#          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#          chmod +x kubectl
#          sudo mv kubectl /usr/local/bin/

#      - name: Configure kubeconfig
#        run: |
#          mkdir -p $HOME/.kube
#          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
#          export KUBECONFIG=$HOME/.kube/config
#          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

#      - name: Debug kubectl config
#        run: |
#          echo "Verificando configuración de kubectl..."
#          kubectl config view
#          kubectl config current-context
#          kubectl get nodes

#      - name: Deploy to Kubernetes
#        run: |
#          kubectl apply -f k8s/deployment.yaml
#          kubectl apply -f k8s/service.yaml
